FROM nextcloud:latest

# Create Pterodactyl container home
RUN mkdir -p /home/container

# Move Nextcloud installation into /home/container
RUN mv /var/www/html /home/container/html

# pterodactyl as owner
RUN chown -R 988:988 /home/container/html

# allow apache to use it too
RUN chmod -R g+rwX /home/container/html && \
    usermod -aG 988 www-data

# set working dir
WORKDIR /home/container


ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
