name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug - Show GitHub actor
        run: echo "Pushing as ${{ github.actor }}"

      - name: Debug - Verify Docker login user
        run: cat ~/.docker/config.json

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/pterodactyl-nextcloud" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:latest
